configFiles:
  Debug: Configs/Debug.xcconfig
  Release: Configs/Release.xcconfig
name: Area51
options:
  bundleIdPrefix: com.gellci
  transitivelyLinkDependencies: true
include:
  - Area51/Area51.yml
  - Area51Tests/Area51Tests.yml
  - Core/Core.yml
  - CoreAPI/CoreAPI.yml
  - ImageService/ImageService.yml
  - ListingService/ListingService.yml
